# This kustomization can be used to remotely install all Crossplane CRDs
# by running kubectl apply -k https://github.com/crossplane/crossplane//cluster?ref=master
resources:
- charts/crossplane/crds/apiextensions.crossplane.io_compositeresourcedefinitions.yaml
- charts/crossplane/crds/apiextensions.crossplane.io_compositions.yaml
- charts/crossplane/crds/pkg.crossplane.io_configurationrevisions.yaml
- charts/crossplane/crds/pkg.crossplane.io_configurations.yaml
- charts/crossplane/crds/pkg.crossplane.io_providerrevisions.yaml
- charts/crossplane/crds/pkg.crossplane.io_providers.yaml
- charts/crossplane/crds/workload.crossplane.io_kubernetesapplicationresources.yaml
- charts/crossplane/crds/workload.crossplane.io_kubernetesapplications.yaml
- charts/crossplane/crds/workload.crossplane.io_kubernetestargets.yaml
